name: Stub CI
on: [push]
jobs:
  stub-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo 'PASS'
      - name: Package
        run: head -c 200000 < /dev/urandom > testing-craft.tbz
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: testing-craft.tbz
          retention-days: 1
